apiVersion: v1
kind: PersistentVolume
metadata:
  name: boiler-plate-uploads-storage-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/arffy/boiler_plate_express_rest/uploads # <â€” path inside your VM, pointing to physical folder
    type: DirectoryOrCreate # auto-creates directory if missing
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: boiler-plate-uploads-storage-pvc
  namespace: boiler-plate
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: boiler-plate-express-rest
  namespace: boiler-plate
  labels:
    app: boiler-plate-express-rest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: boiler-plate-express-rest
  template:
    metadata:
      labels:
        app: boiler-plate-express-rest
    spec:
      containers:
        - name: boiler-plate-express-rest
          image: nexus.arffy.com/projects/boiler_plate_express_rest:209208f7
          ports:
            - containerPort: 3000
          env:
            - name: SEED_DB # to make seeders run only one time (for first replica only initially replicas: 1 and make deploy. then kubectl scale deployment boiler-plate-express-rest --replicas=2)
              value: "true"
            - name: TZ
              value: "UTC"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          volumeMounts:
            - name: uploads-storage
              mountPath: /home/arffy/boiler_plate_express_rest/uploads
      volumes:
        - name: uploads-storage
          persistentVolumeClaim:
            claimName: boiler-plate-uploads-storage-pvc
      imagePullSecrets:
        - name: docker-auth
